//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("ShellProgressBar")]
[assembly: System.Reflection.AssemblyDescription("ShellProgressBar - a progressbar for your console applications")]
[assembly: System.Reflection.AssemblyProduct("ShellProgressBar")]
[assembly: System.Reflection.AssemblyCopyright("Martijn Laarman MIT LICENSED")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.Guid("07E5CFA3-CF5F-4D17-874C-8D5CC6FA3E73")]
[assembly: System.Reflection.AssemblyVersion("3.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.0")]


